# Codecov configuration for e-bash project
# https://docs.codecov.com/docs/codecov-yaml

# Coverage targets
coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    # Overall project coverage
    project:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: error

    # Patch coverage (new code in PR)
    patch:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error

# Flag configuration for parallel uploads
flags:
  shellspec-ubuntu:
    # All 4 chunks upload with this flag
    carryforward: true

  shellspec-macos:
    # MacOS chunks (if applicable)
    carryforward: true

# Comment configuration for PRs
comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

# Ignore paths
ignore:
  - "spec/**"
  - "demos/**"
  - "coverage/**"
  - "report/**"
  - ".github/**"
  - "*.md"
